name: "[gcp] build and deploy an image app"

# trigger the workflow when a push is made on the develop branch
on:
  push:
    # only trigger a new build when a commit is pushed to master
    branches:
      - main

# environment variables used on the respective workflow
env:
  # google cloud platform credentials (they come from github secrets)
  GCP_ARTIFACT_REGISTRY_REPO_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPO_NAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  # docker variables
  IMAGE_NAME: canon-site
  # canon env secrets
  CANON_CMS_DB: ${{ secrets.CANON_CMS_DB }}
  CANON_CMS_CUBES: ${{ secrets.CANON_CMS_CUBES }}
  FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
  # canon env variables
  CANON_API: "http://localhost:3300"
  CANON_LANGUAGE_DEFAULT: "en"
  CANON_LANGUAGES: "en"
  CANON_CMS_ENABLE: "true"

jobs:
  # builds the new docker image via google cloude build
  build:
    name: Build Docker Image via Cloud Build
    runs-on: ubuntu-latest
    #environment: develop_environment
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker Image
        run: |-
          gcloud builds submit \
            --quiet \
            --tag us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REGISTRY_REPO_NAME/$IMAGE_NAME:latest-dev
  # deploys the recently created docker image via google cloude build
  deploy:
    needs: build
    name: Deploy Docker Image to Cloud Run
    runs-on: ubuntu-latest
    environment: develop_environment
    steps:
      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Deploy Image to Cloud Run
        run: |-
          gcloud run deploy ${{ env.IMAGE_NAME }} \
            --image=us-central1-docker.pkg.dev/${{env.GCP_PROJECT_ID}}/${{env.GCP_ARTIFACT_REGISTRY_REPO_NAME}}/${{env.IMAGE_NAME}}:latest-dev \
            --region=us-central1 \
            --port=3300 \
            --set-env-vars=CANON_API=${{ env.CANON_API }} \
            --set-env-vars=CANON_LANGUAGE_DEFAULT=${{ env.CANON_LANGUAGE_DEFAULT }} \
            --set-env-vars=CANON_LANGUAGES=${{ env.CANON_LANGUAGES }} \
            --set-env-vars=CANON_CMS_ENABLE=${{ env.CANON_CMS_ENABLE }} \
            --set-env-vars=CANON_CMS_DB=${{ env.CANON_CMS_DB }} \
            --set-env-vars=CANON_CMS_CUBES=${{ env.CANON_CMS_CUBES }} \
            --set-env-vars=FLICKR_API_KEY=${{ env.FLICKR_API_KEY }} \
            --allow-unauthenticated