name: "[Google Cloud] Build an Staging Docker Image into Artifact Registry"

# trigger the workflow when a push is committed to the staging branch
# IMPORTANT: Please Set Up Branch Protection to Prohibit Direct Commits to Staging Branch
on:
  push:
    branches:
      - staging

# environment variables used for the respective instance (edit as needed)
env:
  # docker variables
  IMAGE_NAME: <PROJECT_NAME>-site-staging
  IMAGE_TAG: latest-staging
  # google cloud secrets (using github secrets)
  GCP_ARTIFACT_REGISTRY_REPO_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPO_NAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  # builds the new docker image via cloud build
  build:
    name: Build the Docker Image via Cloud Build
    runs-on: ubuntu-latest
    # IMPORTANT: setup staging environment in github environments
    environment: staging_environment
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker Image
        run: |-
          gcloud builds submit \
            --quiet \
            --timeout=20m \
            --tag us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REGISTRY_REPO_NAME/$IMAGE_NAME:$IMAGE_TAG